api_platform:
    title: 'CreativePizza'
    description: 'CRT-SYMFONY-5'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
