version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: pizza
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 5432:5432
   
     
  app:
    build:
      context: ./docker/php-fpm
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    depends_on:
      - db
    
    volumes:
      - .:/var/www/

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"


